server:
  port: 8888


spring:
  cloud:
    config:
      server:

        git:
          uri: https://github.com/tothemoon9954/FileRepo.git
          default-label: main
          search-paths: resources

  application:
    name: configServer

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

encrypt:
  key: asdlfkjalsdfjioasjdfoijaosnveioano2lkjasdfoi@IOjsdfoiasdfonoinsgd

