server:
  port: 8888


spring:
  profiles:
    active: profile1

  cloud:
    config:
      server:
        git:
          uri: https://github.com/tothemoon9954/config-server.git
          default-label: main
          search-paths: src/main/resources/test1

---
spring:
  profiles: profile2

  cloud:
    config:
      server:
        git:
          uri: https://github.com/tothemoon9954/config-server.git
          default-label: main
          search-paths: src/main/resources

  application:
    name: server

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

encrypt:
  key: asdlfkjalsdfjioasjdfoijaosnveioano2lkjasdfoi@IOjsdfoiasdfonoinsgd


